"""add job_status

Revision ID: 694f78ca196a
Revises: a77341ec6073
Create Date: 2022-06-14 15:43:23.068706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '694f78ca196a'
down_revision = 'a77341ec6073'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.add_column('posts', sa.Column('job_status', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'job_status')
    # ### end Alembic commands ###
