"""create job table

Revision ID: a77341ec6073
Revises: 88843e976855
Create Date: 2022-06-14 14:53:20.264524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a77341ec6073'
down_revision = '88843e976855'
branch_labels = None
depends_on = None


def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('course', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'course')
    # ### end Alembic commands ###

